# Generated by Django 5.2.6 on 2025-09-12 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='created_at',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='title',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='created_at',
            new_name='voted_at',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='poll',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='description',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='poll',
        ),
    ]
