# Generated by Django 4.2.24 on 2025-09-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_created_at_poll_pub_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.AddField(
            model_name='vote',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
